export const surveyData = [
  {
    "Timestamp": "2026-01-05 13:25:18.462",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "4-6 hours",
    "Platforms you use most (max 2)  ": "Whatsapp, Instagram",
    "How often do you post on social media?  ": "2-3 times a week",
    "You interact more through  ": "DMs/ Private chats",
    "My texting style is usually  ": "Emotional and expressive",
    "I mostly use emojis to express  ": "Mood",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "INFJ",
    "I consider myself more  ": "Introverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Helpful for personalization"
  },
  {
    "Timestamp": "2026-01-05 14:42:42.377",
    "Age Group": "16-20",
    "Gender": "Male",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "8 + hours",
    "Platforms you use most (max 2)  ": "Youtube, Whatsapp, Instagram",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "Likes / reactions",
    "My texting style is usually  ": "Short and direct",
    "I mostly use emojis to express  ": "I dont use much",
    "Did u take any personality tests ?": "I dont know",
    "What is your personality type ?\n": "good",
    "I consider myself more  ": "Depends",
    "I value online privacy  ": 1,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 4,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-05 14:45:39.898",
    "Age Group": "20-25",
    "Gender": "Female",
    "Which of these best describes you?  ": "Working professional",
    "Average time you spend online daily": "<2 hours",
    "Platforms you use most (max 2)  ": "Whatsapp, Instagram",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "I dont interact much",
    "My texting style is usually  ": "Short and direct",
    "I mostly use emojis to express  ": "Mood",
    "Did u take any personality tests ?": "I dont know",
    "What is your personality type ?\n": "Openness",
    "I consider myself more  ": "Ambiverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-05 14:53:03.705",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "2-4 hours",
    "Platforms you use most (max 2)  ": "Youtube, Instagram",
    "How often do you post on social media?  ": "Multiple times a day",
    "You interact more through  ": "Likes / reactions",
    "My texting style is usually  ": "Emoji heavy",
    "I mostly use emojis to express  ": "Sarcasm/ fun",
    "Did u take any personality tests ?": "I dont know",
    "What is your personality type ?\n": "I don't know ",
    "I consider myself more  ": "Introverted",
    "I value online privacy  ": 1,
    "I was aware that AI can infer personality from my digital behaviour  ": 1,
    "Do you think AI personality predictions are accurate  ": 2,
    "AI inferring personality without asking is  ": "Helpful for personalization"
  },
  {
    "Timestamp": "2026-01-05 14:53:08.193",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "<2 hours",
    "Platforms you use most (max 2)  ": "Snapchat",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "I dont interact much",
    "My texting style is usually  ": "Thoughtful and long",
    "I mostly use emojis to express  ": "I dont use much",
    "Did u take any personality tests ?": "I dont know",
    "What is your personality type ?\n": "My personality type traits, feeling.",
    "I consider myself more  ": "Depends",
    "I value online privacy  ": 1,
    "I was aware that AI can infer personality from my digital behaviour  ": 1,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-05 15:00:42.555",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "4-6 hours",
    "Platforms you use most (max 2)  ": "Youtube, Instagram",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "I dont interact much",
    "My texting style is usually  ": "Short and direct",
    "I mostly use emojis to express  ": "I dont use much",
    "Did u take any personality tests ?": "I dont know",
    "What is your personality type ?\n": "Ambivert",
    "I consider myself more  ": "Ambiverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 4,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-05 15:06:28.148",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "<2 hours",
    "Platforms you use most (max 2)  ": "Youtube, Whatsapp",
    "How often do you post on social media?  ": "Never",
    "You interact more through  ": "DMs/ Private chats",
    "My texting style is usually  ": "Short and direct",
    "I mostly use emojis to express  ": "Mood",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "INTP",
    "I consider myself more  ": "Introverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 3,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-05 15:09:13.105",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "2-4 hours",
    "Platforms you use most (max 2)  ": "Whatsapp, Instagram",
    "How often do you post on social media?  ": "2-3 times a week",
    "You interact more through  ": "Likes / reactions",
    "My texting style is usually  ": "Short and direct",
    "I mostly use emojis to express  ": "Mood",
    "Did u take any personality tests ?": "I dont know",
    "What is your personality type ?\n": "No",
    "I consider myself more  ": "Extroverted",
    "I value online privacy  ": 2,
    "I was aware that AI can infer personality from my digital behaviour  ": 1,
    "Do you think AI personality predictions are accurate  ": 2,
    "AI inferring personality without asking is  ": "Helpful for personalization"
  },
  {
    "Timestamp": "2026-01-05 15:25:14.995",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "8 + hours",
    "Platforms you use most (max 2)  ": "Instagram, Canva or Google ",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "I dont interact much",
    "My texting style is usually  ": "Thoughtful and long",
    "I mostly use emojis to express  ": "Sarcasm/ fun",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "INFJ",
    "I consider myself more  ": "Introverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Helpful for personalization"
  },
  {
    "Timestamp": "2026-01-05 15:40:41.850",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "4-6 hours",
    "Platforms you use most (max 2)  ": "Youtube, Instagram",
    "How often do you post on social media?  ": "2-3 times a week",
    "You interact more through  ": "Likes / reactions",
    "My texting style is usually  ": "Emoji heavy",
    "I mostly use emojis to express  ": "Sarcasm/ fun",
    "Did u take any personality tests ?": "I dont know",
    "What is your personality type ?\n": "No",
    "I consider myself more  ": "Extroverted",
    "I value online privacy  ": 3,
    "I was aware that AI can infer personality from my digital behaviour  ": 3,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Helpful for personalization"
  },
  {
    "Timestamp": "2026-01-05 16:30:38.226",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "4-6 hours",
    "Platforms you use most (max 2)  ": "Whatsapp, Instagram",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "Likes / reactions",
    "My texting style is usually  ": "Short and direct",
    "I mostly use emojis to express  ": "Sarcasm/ fun",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "INFP",
    "I consider myself more  ": "Introverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-05 17:04:24.178",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "2-4 hours",
    "Platforms you use most (max 2)  ": "Youtube, Instagram",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "Likes / reactions",
    "My texting style is usually  ": "Short and direct",
    "I mostly use emojis to express  ": "Mood",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "Infp",
    "I consider myself more  ": "Introverted",
    "I value online privacy  ": 4,
    "I was aware that AI can infer personality from my digital behaviour  ": 4,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-05 17:23:55.765",
    "Age Group": "16-20",
    "Gender": "Male",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "8 + hours",
    "Platforms you use most (max 2)  ": "Youtube, Whatsapp",
    "How often do you post on social media?  ": "Once a day",
    "You interact more through  ": "DMs/ Private chats",
    "My texting style is usually  ": "Short and direct",
    "I mostly use emojis to express  ": "I dont use much",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "INTJ",
    "I consider myself more  ": "Introverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 4,
    "Do you think AI personality predictions are accurate  ": 4,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-05 18:07:10.486",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "6-8 hours",
    "Platforms you use most (max 2)  ": "Youtube, Whatsapp, Instagram",
    "How often do you post on social media?  ": "Multiple times a day",
    "You interact more through  ": "Comments/ public replies",
    "My texting style is usually  ": "Thoughtful and long",
    "I mostly use emojis to express  ": "Sarcasm/ fun",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "INFJ",
    "I consider myself more  ": "Ambiverted",
    "I value online privacy  ": 3,
    "I was aware that AI can infer personality from my digital behaviour  ": 3,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-05 18:25:48.746",
    "Age Group": "20-25",
    "Gender": "Female",
    "Which of these best describes you?  ": "Working professional",
    "Average time you spend online daily": "2-4 hours",
    "Platforms you use most (max 2)  ": "Whatsapp, Instagram",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "I dont interact much",
    "My texting style is usually  ": "Emoji heavy",
    "I mostly use emojis to express  ": "Softening the tone",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "INTJ",
    "I consider myself more  ": "Introverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 4,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-05 18:38:04.988",
    "Age Group": "20-25",
    "Gender": "Female",
    "Which of these best describes you?  ": "Working professional",
    "Average time you spend online daily": "6-8 hours",
    "Platforms you use most (max 2)  ": "Youtube, Whatsapp, Instagram",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "DMs/ Private chats",
    "My texting style is usually  ": "Short and direct",
    "I mostly use emojis to express  ": "I dont use much",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "INFJ",
    "I consider myself more  ": "Introverted",
    "I value online privacy  ": 4,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 4,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-05 21:05:24.419",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "6-8 hours",
    "Platforms you use most (max 2)  ": "Youtube, Instagram",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "Likes / reactions",
    "My texting style is usually  ": "Thoughtful and long",
    "I mostly use emojis to express  ": "Softening the tone",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "ENFP",
    "I consider myself more  ": "Extroverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 4,
    "AI inferring personality without asking is  ": "Helpful for personalization"
  },
  {
    "Timestamp": "2026-01-05 22:44:37.399",
    "Age Group": "25+",
    "Gender": "Female",
    "Which of these best describes you?  ": "Working professional",
    "Average time you spend online daily": "4-6 hours",
    "Platforms you use most (max 2)  ": "Youtube, Whatsapp, Linkedin",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "DMs/ Private chats",
    "My texting style is usually  ": "Emotional and expressive",
    "I mostly use emojis to express  ": "Mood",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "INFJ",
    "I consider myself more  ": "Introverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Helpful for personalization"
  },
  {
    "Timestamp": "2026-01-06 00:11:32.815",
    "Age Group": "20-25",
    "Gender": "Female",
    "Which of these best describes you?  ": "Working professional",
    "Average time you spend online daily": "4-6 hours",
    "Platforms you use most (max 2)  ": "Youtube, Whatsapp, Instagram",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "DMs/ Private chats",
    "My texting style is usually  ": "Emotional and expressive",
    "I mostly use emojis to express  ": "Mood",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "ENFJ",
    "I consider myself more  ": "Extroverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-06 00:23:07.758",
    "Age Group": "20-25",
    "Gender": "Female",
    "Which of these best describes you?  ": "Working professional",
    "Average time you spend online daily": "6-8 hours",
    "Platforms you use most (max 2)  ": "Youtube, Whatsapp, Snapchat",
    "How often do you post on social media?  ": "Once a day",
    "You interact more through  ": "Likes / reactions",
    "My texting style is usually  ": "Emotional and expressive",
    "I mostly use emojis to express  ": "Sarcasm/ fun",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "INFP",
    "I consider myself more  ": "Extroverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-06 11:39:02.879",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "8 + hours",
    "Platforms you use most (max 2)  ": "Youtube, Instagram",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "I dont interact much",
    "My texting style is usually  ": "Thoughtful and long",
    "I mostly use emojis to express  ": "Mood",
    "Did u take any personality tests ?": "I dont know",
    "What is your personality type ?\n": "Sweet kind loving personality",
    "I consider myself more  ": "Depends",
    "I value online privacy  ": 3,
    "I was aware that AI can infer personality from my digital behaviour  ": 2,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-06 12:39:18.706",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "6-8 hours",
    "Platforms you use most (max 2)  ": "Youtube, Whatsapp",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "I dont interact much",
    "My texting style is usually  ": "Short and direct",
    "I mostly use emojis to express  ": "I dont use much",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "ISFP",
    "I consider myself more  ": "Ambiverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 4,
    "AI inferring personality without asking is  ": "Helpful for personalization"
  },
  {
    "Timestamp": "2026-01-06 13:27:22.250",
    "Age Group": "20-25",
    "Gender": "Female",
    "Which of these best describes you?  ": "Working professional",
    "Average time you spend online daily": "2-4 hours",
    "Platforms you use most (max 2)  ": "Youtube, Linkedin",
    "How often do you post on social media?  ": "2-3 times a week",
    "You interact more through  ": "DMs/ Private chats",
    "My texting style is usually  ": "Thoughtful and long",
    "I mostly use emojis to express  ": "Sarcasm/ fun",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "ENFJ",
    "I consider myself more  ": "Extroverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Helpful for personalization"
  },
  {
    "Timestamp": "2026-01-06 16:29:30.984",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "2-4 hours",
    "Platforms you use most (max 2)  ": "Youtube, Pintrest",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "DMs/ Private chats",
    "My texting style is usually  ": "Minimal/no emojis",
    "I mostly use emojis to express  ": "Mood",
    "Did u take any personality tests ?": "I dont know",
    "What is your personality type ?\n": "Ambivert",
    "I consider myself more  ": "Ambiverted",
    "I value online privacy  ": 4,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 2,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-06 23:38:50.632",
    "Age Group": "25+",
    "Gender": "Male",
    "Which of these best describes you?  ": "Working professional",
    "Average time you spend online daily": "2-4 hours",
    "Platforms you use most (max 2)  ": "Youtube, Whatsapp",
    "How often do you post on social media?  ": "Never",
    "You interact more through  ": "DMs/ Private chats",
    "My texting style is usually  ": "Short and direct",
    "I mostly use emojis to express  ": "Sarcasm/ fun",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "ISTJ",
    "I consider myself more  ": "Ambiverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 4,
    "Do you think AI personality predictions are accurate  ": 1,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-07 07:38:07.532",
    "Age Group": "16-20",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "<2 hours",
    "Platforms you use most (max 2)  ": "Youtube, Instagram",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "I dont interact much",
    "My texting style is usually  ": "Emotional and expressive",
    "I mostly use emojis to express  ": "Sarcasm/ fun",
    "Did u take any personality tests ?": "I dont know",
    "What is your personality type ?\n": "Cute,bubbly,sweet and trusts everyone easily",
    "I consider myself more  ": "Ambiverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 1,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-07 18:06:25.144",
    "Age Group": "20-25",
    "Gender": "Female",
    "Which of these best describes you?  ": "Working professional",
    "Average time you spend online daily": "4-6 hours",
    "Platforms you use most (max 2)  ": "Whatsapp, Snapchat, Linkedin",
    "How often do you post on social media?  ": "2-3 times a week",
    "You interact more through  ": "DMs/ Private chats",
    "My texting style is usually  ": "Minimal/no emojis",
    "I mostly use emojis to express  ": "I dont use much",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "Introvert",
    "I consider myself more  ": "Introverted",
    "I value online privacy  ": 5,
    "I was aware that AI can infer personality from my digital behaviour  ": 5,
    "Do you think AI personality predictions are accurate  ": 3,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-07 18:10:04.758",
    "Age Group": "11-15",
    "Gender": "Female",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "6-8 hours",
    "Platforms you use most (max 2)  ": "Youtube, Snapchat, Pintrest",
    "How often do you post on social media?  ": "Multiple times a day",
    "You interact more through  ": "Likes / reactions",
    "My texting style is usually  ": "Emotional and expressive",
    "I mostly use emojis to express  ": "Sarcasm/ fun",
    "Did u take any personality tests ?": "MBTI ( INTJ, ESFP etc)",
    "What is your personality type ?\n": "Funny",
    "I consider myself more  ": "Extroverted",
    "I value online privacy  ": 3,
    "I was aware that AI can infer personality from my digital behaviour  ": 3,
    "Do you think AI personality predictions are accurate  ": 5,
    "AI inferring personality without asking is  ": "Depends on usage"
  },
  {
    "Timestamp": "2026-01-07 18:12:02.899",
    "Age Group": "11-15",
    "Gender": "Male",
    "Which of these best describes you?  ": "Student",
    "Average time you spend online daily": "4-6 hours",
    "Platforms you use most (max 2)  ": "Youtube, Whatsapp, Instagram, Pintrest",
    "How often do you post on social media?  ": "Once a day",
    "You interact more through  ": "I dont interact much",
    "My texting style is usually  ": "Short and direct",
    "I mostly use emojis to express  ": "Softening the tone",
    "Did u take any personality tests ?": "I dont know",
    "What is your personality type ?\n": "silent",
    "I consider myself more  ": "Ambiverted",
    "I value online privacy  ": 4,
    "I was aware that AI can infer personality from my digital behaviour  ": 4,
    "Do you think AI personality predictions are accurate  ": 4,
    "AI inferring personality without asking is  ": "Unethical, invades privacy"
  },
  {
    "Timestamp": "2026-01-07 18:15:20.600",
    "Age Group": "25+",
    "Gender": "Male",
    "Which of these best describes you?  ": "Working professional",
    "Average time you spend online daily": "4-6 hours",
    "Platforms you use most (max 2)  ": "Youtube, Whatsapp, Linkedin",
    "How often do you post on social media?  ": "Rarely",
    "You interact more through  ": "DMs/ Private chats",
    "My texting style is usually  ": "Short and direct",
    "I mostly use emojis to express  ": "I dont use much",
    "Did u take any personality tests ?": "I dont know",
    "What is your personality type ?\n": "Mature",
    "I consider myself more  ": "Ambiverted",
    "I value online privacy  ": 3,
    "I was aware that AI can infer personality from my digital behaviour  ": 3,
    "Do you think AI personality predictions are accurate  ": 4,
    "AI inferring personality without asking is  ": "Helpful for personalization"
  }
];
